services:
  server:
    container_name: server
    build: ./web
    env_file: .env
    volumes:
      - backend:/backend
    ports:
      - "8000:8000"

volumes:
   backend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./web/service/backend