# Generated by Django 5.1.2 on 2024-10-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Custom_User',
        ),
    ]
